//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.BusinessObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POCDBEntities : DbContext
    {
        public POCDBEntities()
            : base("name=POCDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CL_ROLES> CL_ROLES { get; set; }
        public virtual DbSet<CL_USERS> CL_USERS { get; set; }
        public virtual DbSet<INFORMATION> INFORMATION { get; set; }
    }
}
