//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CL_ROLES
    {
        public int ROLE_ID { get; set; }
        public string ROLE_DESC { get; set; }
    }
}
