//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POC.BusinessObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMATION
    {
        public int INFO_ID { get; set; }
        public string ID_NO { get; set; }
        public string SURNAME { get; set; }
        public string FIRST_NAMES { get; set; }
        public string LANGUAGE { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CELLNUM { get; set; }
        public string TELEPHONE { get; set; }
        public Nullable<System.DateTime> APPLICATION_DATE { get; set; }
        public string BENEFITPACK { get; set; }
        public string SGC { get; set; }
        public string TINSTANCE { get; set; }
        public Nullable<int> AMP { get; set; }
        public string TINDEX { get; set; }
        public Nullable<System.DateTime> CONNECTION_DATE { get; set; }
        public string METERNUMBER { get; set; }
        public string ALGORITHM { get; set; }
        public string TOKEN { get; set; }
        public string EBC { get; set; }
        public string TRFR { get; set; }
        public string POLE { get; set; }
        public string SEALING { get; set; }
        public string COCNUMBER { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string PS_FEEDBACK { get; set; }
        public string LATITUDE { get; set; }
        public string LONGTUDE { get; set; }
        public byte[] PHOTO { get; set; }
        public Nullable<System.DateTime> SYNC_DATE { get; set; }
    }
}
